services:
  - type: web
    name: IMMO-360-BACKEND
    runtime: node
    plan: Starter
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
