services:
  - type: web
    name: IMMO-360-BACKEND
    runtime: node
    plan: Starter
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
