export type Property = {
  id: number;
  image: string;
  type: string;
  price: string;
  rating: number;
  reviews: number;
  rooms: string;
  kitchen: string;
  parking: string;
  bath: string;
  location: string;
  phone: string;
  owner: string;
  caution: string;
  advance: string;
  visit: string;
};

export const properties: Property[] = [
  {
    id: 1,
    image: "/assets/Rectangle 7 (1).png",
    type: "Villa Duplex avec Piscine",
    price: "200.000 XOF / mois",
    rating: 4.9,
    reviews: 3006,
    rooms: "04 Chambres",
    kitchen: "01 Cuisine",
    parking: "01 Garage",
    bath: "02 Toilettes",
    location: "Agbalépédo, Lomé-Togo",
    phone: "(+228) 90 90 90 90",
    owner: "Reed Belca",
    caution: "06 mois",
    advance: "08 mois",
    visit: "2000 FCFA",
  },
  {
    id: 2,
    image: "/assets/Rectangle 7 (2).png",
    type: "Pièce studio",
    price: "7 500/Mois",
    rating: 4.5,
    reviews: 2436,
    rooms: "02 Chambres",
    kitchen: "Pas de cuisine",
    parking: "Pas de Parking",
    bath: "WC, douche interne",
    location: "Adidogomé, Lomé-Togo",
    phone: "(+228) 90 80 70 60",
    owner: "Alima Kossi",
    caution: "03 mois",
    advance: "02 mois",
    visit: "1500 FCFA",
  },
  {
    id: 3,
    image: "/assets/Rectangle 7 (3).png",
    type: "Villa Duplex",
    price: "22 000/Mois",
    rating: 4.8,
    reviews: 2006,
    rooms: "04 Chambres",
    kitchen: "Cuisine interne",
    parking: "02 Voitures",
    bath: "WC, douche interne",
    location: "Hédzranawoé, Lomé-Togo",
    phone: "(+228) 90 70 60 50",
    owner: "Yao Mensah",
    caution: "05 mois",
    advance: "06 mois",
    visit: "1800 FCFA",
  },
  {
    id: 4,
    image: "/assets/Rectangle 7 (5).png",
    type: "Appartement studio",
    price: "9 000/Mois",
    rating: 4.2,
    reviews: 6402,
    rooms: "01 Chambre",
    kitchen: "Cuisine interne",
    parking: "01 Voiture",
    bath: "WC, douche interne",
    location: "Baguida, Lomé-Togo",
    phone: "(+228) 90 60 50 40",
    owner: "Kofi Agbeko",
    caution: "04 mois",
    advance: "04 mois",
    visit: "1200 FCFA",
  },
  {
    id: 5,
    image: "/assets/Rectangle 7 (4).png",
    type: "Maison familiale",
    price: "18 500/Mois",
    rating: 4.7,
    reviews: 1987,
    rooms: "05 Chambres",
    kitchen: "Cuisine interne",
    parking: "03 Voitures",
    bath: "WC, douche interne",
    location: "Kodjoviakopé, Lomé-Togo",
    phone: "(+228) 90 50 40 30",
    owner: "Selorm Amuzu",
    caution: "07 mois",
    advance: "09 mois",
    visit: "2200 FCFA",
  },
  {
    id: 6,
    image: "/assets/Rectangle 7 (6).png",
    type: "Studio moderne",
    price: "8 500/Mois",
    rating: 4.3,
    reviews: 1845,
    rooms: "01 Chambre",
    kitchen: "Cuisine interne",
    parking: "Pas de Parking",
    bath: "WC, douche interne",
    location: "Ablogamé, Lomé-Togo",
    phone: "(+228) 90 40 30 20",
    owner: "Djeneba Toure",
    caution: "03 mois",
    advance: "03 mois",
    visit: "1600 FCFA",
  },
  {
    id: 7,
    image: "/assets/Rectangle 7 (7).png",
    type: "Duplex spacieux",
    price: "25 000/Mois",
    rating: 4.8,
    reviews: 2140,
    rooms: "04 Chambres",
    kitchen: "Cuisine interne",
    parking: "03 Voitures",
    bath: "WC, douche interne",
    location: "Aného, Maritime-Togo",
    phone: "(+228) 90 30 20 10",
    owner: "Mawuena Assan",
    caution: "08 mois",
    advance: "10 mois",
    visit: "2500 FCFA",
  },
  {
    id: 8,
    image: "/assets/Rectangle 7 (8).png",
    type: "Apartment luxe",
    price: "30 000/Mois",
    rating: 4.9,
    reviews: 2721,
    rooms: "03 Chambres",
    kitchen: "Cuisine interne",
    parking: "02 Voitures",
    bath: "WC, douche interne",
    location: "Tsévié, Maritime-Togo",
    phone: "(+228) 90 20 10 00",
    owner: "Kossi Amegayibor",
    caution: "09 mois",
    advance: "11 mois",
    visit: "2700 FCFA",
  },
  {
    id: 9,
    image: "/assets/Rectangle 7.png",
    type: "Maison d’architecte",
    price: "35 000/Mois",
    rating: 4.9,
    reviews: 3150,
    rooms: "05 Chambres",
    kitchen: "Cuisine interne",
    parking: "04 Voitures",
    bath: "WC, douche interne",
    location: "Kégué, Lomé-Togo",
    phone: "(+228) 90 10 00 90",
    owner: "Belinda Soglo",
    caution: "10 mois",
    advance: "12 mois",
    visit: "3000 FCFA",
  },
];
